/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import Model.Cliente;
import Model.Produto;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class Principal extends javax.swing.JFrame {

    int idCliente;

    public Principal() {
        initComponents();
        painelAbas.setVisible(true);
        listarCli();
        listarProd();

        //Populando Combo Box Cliente
        ClienteDAO clienteDAO = new ClienteDAO();
        for (Cliente c : clienteDAO.listarCliente()) {
            cbClientes.addItem(c.getName());
        }
    }

    void listarCli() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        modelo.setNumRows(0);
        ClienteDAO cliDAO = new ClienteDAO();
        for (Cliente c : cliDAO.listarCliente()) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getName(),
                c.getAge(),
                c.getTel()
            });
        }
    }

    void listarProd() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        for (Produto p : produtoDAO.listarProdutoDAO()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getDesc(),
                p.getPrice(),
                p.getQuant()
            });
        }
    }

    void buscarProduto(Produto produto) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaBuscaProduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        for (Produto p : produtoDAO.buscarProdutoDAO(produto)) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getDesc(),
                p.getPrice(),
                p.getQuant()
            });
        }
    }

    void limparCampos(String tipo) {

        if (tipo.equals("produto")) {
            txtCodigoProduto.setText("");
            txtNomeProduto.setText("");
            txtDescricaoProduto.setText("");
            txtPrecoProduto.setText("");
            txtQuantidadeProduto.setText("");
            //Habilitando
            txtNomeProduto.setEditable(true);
            txtDescricaoProduto.setEditable(true);
            txtPrecoProduto.setEditable(true);
            txtQuantidadeProduto.setEditable(true);
        } else if (tipo.equals("cliente")) {
            txtCodigoCliente.setText("");
            txtNomeCliente.setText("");
            txtIdadeCliente.setText("");
            txtCelularCliente.setText("");

            //Habilitando
            txtCodigoCliente.setEditable(true);
            txtNomeCliente.setEditable(true);
            txtIdadeCliente.setEditable(true);
            txtCelularCliente.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAbas = new javax.swing.JTabbedPane();
        painelClientes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdadeCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrarCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        txtCelularCliente = new javax.swing.JFormattedTextField();
        painelProdutos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        txtDescricaoProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCadastrarProduto = new javax.swing.JButton();
        btnAlterarProduto = new javax.swing.JButton();
        btnLimparProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        btnExcluirProduto = new javax.swing.JButton();
        txtQuantidadeProduto = new javax.swing.JFormattedTextField();
        txtPrecoProduto = new javax.swing.JFormattedTextField();
        tabelaVenda = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lblQuantItens = new javax.swing.JLabel();
        lblTotalGeral = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantVenda = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDescontoVenda = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox<Object>();
        jLabel18 = new javax.swing.JLabel();
        txtBuscaProduto = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaBuscaProduto = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini ERP by Felipe Oliveira");
        setExtendedState(MAXIMIZED_BOTH);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelAbas.setBackground(new java.awt.Color(215, 229, 229));
        painelAbas.setAutoscrolls(true);
        painelAbas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        painelAbas.setName(""); // NOI18N

        painelClientes.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Cód:");

        txtCodigoCliente.setFocusable(false);

        jLabel2.setText("Nome: ");

        jLabel3.setText("Idade:");

        jLabel4.setText("Cel:");

        btnCadastrarCliente.setText("SALVAR");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("ALTERAR");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("EXCLUIR");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setText("LIMPAR");
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Idade", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaClientes);

        try {
            txtCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelularCliente.setToolTipText("DD+Celular ");

        javax.swing.GroupLayout painelClientesLayout = new javax.swing.GroupLayout(painelClientes);
        painelClientes.setLayout(painelClientesLayout);
        painelClientesLayout.setHorizontalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(painelClientesLayout.createSequentialGroup()
                        .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente))
                            .addGroup(painelClientesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(btnLimparCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluirCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrarCliente)))
                        .addGap(0, 312, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelClientesLayout.setVerticalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(txtIdadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrarCliente)
                        .addComponent(btnAlterarCliente)
                        .addComponent(btnExcluirCliente)
                        .addComponent(btnLimparCliente)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        painelAbas.addTab("Clientes", painelClientes);

        painelProdutos.setBackground(new java.awt.Color(204, 204, 255));
        painelProdutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                painelProdutosFocusGained(evt);
            }
        });

        jLabel5.setText("Cod:");

        txtCodigoProduto.setFocusable(false);

        jLabel6.setText("Nome:");

        jLabel7.setText("Descrição:");

        jLabel8.setText("Quantidade:");

        jLabel9.setText("Preço:");

        btnCadastrarProduto.setText("CADASTRAR");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnAlterarProduto.setText("ALTERAR");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnLimparProduto.setText("LIMPAR");
        btnLimparProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparProdutoActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOME", "DESCRIÇÃO", "PREÇO", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        btnExcluirProduto.setText("EXCLUIR");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        txtQuantidadeProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#######"))));
        txtQuantidadeProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeProdutoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelProdutosLayout = new javax.swing.GroupLayout(painelProdutos);
        painelProdutos.setLayout(painelProdutosLayout);
        painelProdutosLayout.setHorizontalGroup(
            painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutosLayout.createSequentialGroup()
                        .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(54, 54, 54)
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeProduto)))
                    .addGroup(painelProdutosLayout.createSequentialGroup()
                        .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(11, 11, 11)
                                .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelProdutosLayout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarProduto)))
                .addContainerGap())
        );
        painelProdutosLayout.setVerticalGroup(
            painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrarProduto)
                        .addComponent(btnAlterarProduto)
                        .addComponent(btnLimparProduto)
                        .addComponent(btnExcluirProduto)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(466, Short.MAX_VALUE))
        );

        painelAbas.addTab("Produtos", painelProdutos);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel10.setText("TOTAL:");

        tabelaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "PRODUTO", "DESCRIÇÃO", "QUANTIDADE", "VALOR UNITÁRIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaPedidos);

        jLabel11.setText("Quantidade de Itens:");

        lblQuantItens.setText("0");

        lblTotalGeral.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblTotalGeral.setText("0");

        jLabel12.setText("CÓDIGO DO PRODUTO");

        jLabel14.setText("QUANTIDADE");

        txtValorVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVendaActionPerformed(evt);
            }
        });

        jLabel15.setText("VALOR UNITÁRIO:");

        jLabel16.setText("VALOR DESCONTO:");

        jLabel17.setText("CLIENTE:");

        cbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesActionPerformed(evt);
            }
        });

        jLabel18.setText("BUSCAR PRODUTO:");

        txtBuscaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscaProdutoKeyPressed(evt);
            }
        });

        tabelaBuscaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "PRODUTO", "DESCRIÇÃO", "PREÇO", "QUANTIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaBuscaProduto);

        jLabel19.setText("PRODUTO:");

        jButton1.setText("ADICIONAR PRODUTO");

        javax.swing.GroupLayout tabelaVendaLayout = new javax.swing.GroupLayout(tabelaVenda);
        tabelaVenda.setLayout(tabelaVendaLayout);
        tabelaVendaLayout.setHorizontalGroup(
            tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblQuantItens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(55, 55, 55)
                        .addComponent(lblTotalGeral))
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(tabelaVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBuscaProduto))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelaVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelaVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(tabelaVendaLayout.createSequentialGroup()
                                    .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQuantVenda, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtValorVenda, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(81, 81, 81)
                                    .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(tabelaVendaLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        tabelaVendaLayout.setVerticalGroup(
            tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelaVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabelaVendaLayout.createSequentialGroup()
                                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescontoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addGroup(tabelaVendaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuantVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValorVenda))))))
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabelaVendaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(136, 136, 136)
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblQuantItens))
                .addGap(29, 29, 29)
                .addGroup(tabelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTotalGeral))
                .addGap(322, 322, 322))
        );

        painelAbas.addTab("PDV", tabelaVenda);

        getContentPane().add(painelAbas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 1190, -1));

        setBounds(0, 0, 1227, 1154);
    }// </editor-fold>//GEN-END:initComponents

    private void painelProdutosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painelProdutosFocusGained
    }//GEN-LAST:event_painelProdutosFocusGained

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        if (!txtCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Cliente já existe");
        } else if (txtNomeCliente.getText().equals("") || txtIdadeCliente.getText().equals("") || txtCelularCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha os campos: Nome / Idade / Celular");
        } else {
            Cliente cliente = new Cliente(txtNomeCliente.getText(), Integer.parseInt(txtIdadeCliente.getText()), txtCelularCliente.getText());
            ClienteDAO clienteDAO = new ClienteDAO();
            clienteDAO.cadastrarCliente(cliente);
            listarCli();
            String tipo = "cliente";
            limparCampos(tipo);
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed

        if (!txtCodigoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Produto já existe");
        } else if (txtNomeProduto.getText().equals("") || txtPrecoProduto.getText().equals("") || txtQuantidadeProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nome - Preço e Quantidade são obrigatórios");
        } else {
            Produto produto = new Produto();
            produto.setName(txtNomeProduto.getText().toUpperCase());
            produto.setDesc((txtDescricaoProduto.getText().trim().equals("")) ? "Sem Descrição" : txtDescricaoProduto.getText().toUpperCase());

            if (txtPrecoProduto.getText().contains(",")) {
                String precoCorreto = txtPrecoProduto.getText().replace(",", ".");
                produto.setPrice(Float.parseFloat(precoCorreto));
            } else {
                produto.setPrice(Float.parseFloat(txtPrecoProduto.getText()));
            }

            while (txtQuantidadeProduto.getText().contains(",")) {
                JOptionPane.showMessageDialog(this, "Quantidades devem conter apenas números inteiros");
                break;
            } 
            
            produto.setQuant(Integer.parseInt(txtQuantidadeProduto.getText()));

            ProdutoDAO produtoDAO = new ProdutoDAO();
            produtoDAO.cadastrarProduto(produto);
            listarProd();
            String tipo = "produto";
            limparCampos(tipo);
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        //Pegando linha selecionada na tabela
        DefaultTableModel table = (DefaultTableModel) tabelaClientes.getModel();
        int linha = tabelaClientes.getSelectedRow();
        idCliente = (int) table.getValueAt(linha, 0);
        String nomeCliente = table.getValueAt(linha, 1).toString();
        String idadeCliente = table.getValueAt(linha, 2).toString();
        String celCliente = table.getValueAt(linha, 3).toString();

        //Preenchendo Campos do form:
        txtCodigoCliente.setText(Integer.toString(idCliente));
        txtNomeCliente.setText(nomeCliente);
        txtIdadeCliente.setText(idadeCliente);
        txtCelularCliente.setText(celCliente);

        //txtCodigoCliente.setEditable(false);
        txtNomeCliente.setEditable(false);
        txtIdadeCliente.setEditable(false);
        txtCelularCliente.setEditable(false);
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        if (txtCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir");
        } else {
            //0=yes 1=no 2=cancel
            int option = JOptionPane.showConfirmDialog(null, "Deseja Realmente exluir esse cliente?", "", JOptionPane.YES_NO_OPTION);
            System.out.println(option);

            if (option == 0) {
                ClienteDAO cliDAO = new ClienteDAO();
                Cliente cliente = new Cliente();
                cliente.setId(Integer.parseInt(txtCodigoCliente.getText()));
                cliDAO.excluirCliente(cliente);
                listarCli();
                String tipo = "cliente";
                limparCampos(tipo);
            }

        }

    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
        String tipo = "cliente";
        limparCampos(tipo);
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed

        if (!txtCodigoCliente.getText().equals("") && btnAlterarCliente.getText().equals("ALTERAR")) {
            //Habilitando campos
            txtNomeCliente.setEditable(true);
            txtIdadeCliente.setEditable(true);
            txtCelularCliente.setEditable(true);

            //Desabilitando botôes
            btnCadastrarCliente.setEnabled(false);
            btnExcluirCliente.setEnabled(false);
            btnLimparCliente.setEnabled(false);

            btnAlterarCliente.setText("SALVAR ALTERAÇÃO");
        } else if (btnAlterarCliente.getText().equals("SALVAR ALTERAÇÃO")) {
            ClienteDAO cliDAO = new ClienteDAO();

            //costruindo cliente
            Cliente cliente = new Cliente();
            cliente.setId(Integer.parseInt(txtCodigoCliente.getText()));
            cliente.setName(txtNomeCliente.getText());
            cliente.setAge(Integer.parseInt(txtIdadeCliente.getText()));
            cliente.setTel(txtCelularCliente.getText());
            cliDAO.atualizarCliente(cliente);
            btnCadastrarCliente.setEnabled(true);
            btnExcluirCliente.setEnabled(true);
            btnAlterarCliente.setText("ALTERAR");
            listarCli();
            String tipo = "cliente";
            limparCampos(tipo);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para alterar.");
        }
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (txtCodigoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este produto", "Excluir", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                Produto produto = new Produto();
                produto.setId(Integer.parseInt(txtCodigoProduto.getText()));
                produto.setName(txtNomeProduto.getText());
                produto.setDesc(txtDescricaoProduto.getText());
                produto.setPrice(Float.parseFloat(txtPrecoProduto.getText()));
                produto.setQuant(Integer.parseInt(txtQuantidadeProduto.getText()));

                ProdutoDAO pDAO = new ProdutoDAO();
                pDAO.excluirProduto(produto);
                JOptionPane.showMessageDialog(null, "Produto Excluído com sucesso");
                listarProd();
                String tipo = "produto";
                limparCampos(tipo);
            }
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        DefaultTableModel table = (DefaultTableModel) tabelaProdutos.getModel();
        int linha = tabelaProdutos.getSelectedRow();
        String idProduto = table.getValueAt(linha, 0).toString();
        String nomeProduto = table.getValueAt(linha, 1).toString();
        String descProduto = table.getValueAt(linha, 2).toString();
        String precoProduto = table.getValueAt(linha, 3).toString();
        String quantProduto = table.getValueAt(linha, 4).toString();
        //Preenchendo Campos do form:

        txtCodigoProduto.setText(idProduto);
        txtNomeProduto.setText(nomeProduto);
        txtDescricaoProduto.setText(descProduto);
        txtQuantidadeProduto.setText(quantProduto);
        txtPrecoProduto.setText(precoProduto);

        txtCodigoProduto.setEditable(false);
        txtNomeProduto.setEditable(false);
        txtDescricaoProduto.setEditable(false);
        txtQuantidadeProduto.setEditable(false);
        txtPrecoProduto.setEditable(false);
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void btnLimparProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparProdutoActionPerformed
        String tipo = "produto";
        limparCampos(tipo);
    }//GEN-LAST:event_btnLimparProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        if (!txtCodigoProduto.getText().equals("") && btnAlterarProduto.getText().equals("ALTERAR")) {
            //Habilitando campos
            txtNomeProduto.setEditable(true);
            txtDescricaoProduto.setEditable(true);
            txtPrecoProduto.setEditable(true);
            txtQuantidadeProduto.setEditable(true);

            //Desabilitando botôes
            btnCadastrarProduto.setEnabled(false);
            btnExcluirProduto.setEnabled(false);
            btnLimparProduto.setEnabled(false);

            btnAlterarProduto.setText("SALVAR ALTERAÇÃO");
        } else if (btnAlterarProduto.getText().equals("SALVAR ALTERAÇÃO")) {
            ProdutoDAO prodDAO = new ProdutoDAO();

            //costruindo Produto
            Produto produto = new Produto();
            produto.setId(Integer.parseInt(txtCodigoProduto.getText()));
            produto.setName(txtNomeProduto.getText());
            produto.setDesc(txtDescricaoProduto.getText());
            produto.setPrice(Float.parseFloat(txtPrecoProduto.getText()));
            produto.setQuant(Integer.parseInt(txtQuantidadeProduto.getText()));
            prodDAO.atualizarProduto(produto);
            btnCadastrarProduto.setEnabled(true);
            btnExcluirProduto.setEnabled(true);
            btnLimparProduto.setEnabled(true);
            btnAlterarProduto.setText("ALTERAR");
            //btnAlterarProduto.setText(null);
            String tipo = "produto";
            limparCampos(tipo);
            listarProd();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Produto para alterar.");
        }

    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void txtValorVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVendaActionPerformed

    private void cbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesActionPerformed


    }//GEN-LAST:event_cbClientesActionPerformed

    private void txtBuscaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaProdutoKeyPressed
        if (evt.getKeyCode() == 10) {
            Produto produto = new Produto();
            produto.setName(txtBuscaProduto.getText());

            buscarProduto(produto);

        }

    }//GEN-LAST:event_txtBuscaProdutoKeyPressed

    private void txtQuantidadeProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoFocusLost
        if(!txtQuantidadeProduto.getText().equals("")){
            if(txtQuantidadeProduto.getText().contains("A,B")){
                JOptionPane.showMessageDialog(null, "CONTEM LETRAS");
            }
          JOptionPane.showMessageDialog(null, "Saiu do foco");
        } 
    }//GEN-LAST:event_txtQuantidadeProdutoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnLimparProduto;
    private javax.swing.JComboBox<Object> cbClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblQuantItens;
    private javax.swing.JLabel lblTotalGeral;
    private javax.swing.JTabbedPane painelAbas;
    private javax.swing.JPanel painelClientes;
    private javax.swing.JPanel painelProdutos;
    private javax.swing.JTable tabelaBuscaProduto;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JPanel tabelaVenda;
    private javax.swing.JTextField txtBuscaProduto;
    private javax.swing.JFormattedTextField txtCelularCliente;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtDescontoVenda;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtIdadeCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JFormattedTextField txtPrecoProduto;
    private javax.swing.JTextField txtQuantVenda;
    private javax.swing.JFormattedTextField txtQuantidadeProduto;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
